Repository oSoc20/ArTIFFact-Control, pull requests merged in 2020-07, with the labels that each got.

#26 Feature/sidebar
  package.json
  src/main/main.ts
  src/renderer/actions/SidebarAction.ts
  src/renderer/actions/exampleActions.ts
  src/renderer/actions/index.ts
  src/renderer/app.tsx
  src/renderer/components/Application.tsx
  src/renderer/components/Counter.tsx
  src/renderer/reducers/SidebarReducer.ts
  src/renderer/reducers/exampleReducer.ts
  src/renderer/reducers/index.ts
  src/renderer/screens/About/About.tsx
  src/renderer/screens/Application.tsx
  src/renderer/screens/ConformanceChecks/PeriodicalChecks.tsx
  src/renderer/screens/Dashboard/Dashboard.tsx
  src/renderer/screens/FileChecks/FileChecks.tsx
  src/renderer/screens/Help/Help.tsx
  src/renderer/screens/PeriodicalChecks/PeriodicalChecks.tsx
  src/renderer/screens/Reports/Reports.tsx
  src/renderer/screens/Sidebar/Sidebar.tsx
  src/renderer/screens/Statistics/Statistics.tsx
  src/renderer/store/index.ts
  src/resources/images/logo.svg
  src/resources/images/logoWithLabel.svg
  test/e2e/example.spec.ts
Labels: enhancement, frontend

#52 Feature/check stage2
  src/renderer/actions/FileCheckActions.ts
  src/renderer/assets/icons/icons8-arrow-500.svg
  src/renderer/components/FileCheckDropzone/FileCheckDropzone.tsx
  src/renderer/components/FileCheckStepper/FileCheckStepper.tsx
  src/renderer/reducers/FileCheckReducer.ts
  src/renderer/screens/FileChecks/FileChecks.tsx
  src/renderer/screens/FileChecks/Stage1.tsx
  src/renderer/screens/FileChecks/Stage2.tsx
Labels: code, frontend

#55 Feature/check stage3
  src/renderer/components/FileUploadStages/PickFiles/Stage1.tsx
  src/renderer/components/FileUploadStages/ProcessFiles/Stage3.tsx
Labels: code, frontend

#67 Fix typo in sidebar
  src/renderer/screens/Sidebar/Sidebar.tsx
Labels: bug

#69 Feature/about page
  src/renderer/assets/logos/meemoo_logo.svg
  src/renderer/assets/logos/osoc_logo 1.svg
  src/renderer/screens/About/About.tsx
Labels: code, enhancement, frontend

#77 Feature/conf to disk
  config/Baseline HTML.dpf
  package.json
  src/interfaces/Configuration.tsx
  src/renderer/actions/ConfigurationActions.ts
  src/renderer/components/ConfigurationTable/ConfigurationTable.tsx
  src/renderer/components/CreateConfigStages/Summary/Summary.tsx
  src/renderer/components/FileUploadStages/PickConfiguration/Stage2.tsx
  src/renderer/reducers/ConfigurationReducer.ts
  src/renderer/reducers/index.ts
  src/renderer/screens/Configuration/Configuration.tsx
  tsconfig.json
  webpack-config/webpack.base.config.js
Labels: code, frontend

#78 Feature/style configuration
  src/renderer/assets/icons/icons8-administrative-tools-100.svg
  src/renderer/components/ConfigurationTable/ConfigurationTable.tsx
  src/renderer/components/CreateConfigStages/AddPolicy/AddPolicy.tsx
  src/renderer/components/CreateConfigStages/NameSetter/NameSetter.tsx
  src/renderer/components/CreateConfigStages/PolicyChecker/PolicyChecker.tsx
  src/renderer/components/CreateConfigStages/Report/Report.tsx
  src/renderer/components/CreateConfigStages/StandardPick/StandardPick.tsx
  src/renderer/components/CreateConfigStages/Summary/Summary.tsx
  src/renderer/components/ReportsTable/ReportsTable.tsx
  src/renderer/screens/About/About.tsx
  src/renderer/screens/Configuration/Configuration.tsx
Labels: code, enhancement, frontend

#81 Fix/configuration
  src/renderer/components/ReportDetails/ReportDetails.tsx
  src/renderer/components/ReportsTable/ReportsTable.tsx
  src/renderer/screens/Configuration/Configuration.tsx
Labels: bug, code

#83 Style/dropzone border
  src/renderer/components/FileCheckDropzone/FileCheckDropzone.tsx
  src/renderer/components/FileUploadStages/PickFiles/Stage1.tsx
  src/renderer/screens/Dashboard/Dashboard.tsx
  src/renderer/screens/FileChecks/FileChecks.tsx
Labels: enhancement, frontend

#79 feature/save read report
  package.json
  reports/.placeholder
  src/renderer/actions/ReportActions.ts
  src/renderer/components/ConfigurationTable/ConfigurationTable.tsx
  src/renderer/components/FileUploadStages/ProcessFiles/Stage3.tsx
  src/renderer/components/LastConfigurations/LastConfigurations.tsx
  src/renderer/components/LastReports/LastReports.tsx
  src/renderer/reducers/ConfigurationReducer.ts
  src/renderer/reducers/ReportsReducer.ts
  src/renderer/reducers/index.ts
  src/renderer/screens/Configuration/Configuration.tsx
  src/renderer/screens/Reports/Reports.tsx
  webpack-config/webpack.base.config.js
Labels: code, frontend

#89 Remove temp config
  src/renderer/components/FileUploadStages/PickConfiguration/Stage2.tsx
Labels: bug, code

#91 Fix/linux dev
  build/icon.png
  src/main/main.ts
  src/renderer/reducers/index.ts
Labels: bug, code

#93 Feature/readme
  README.md
  src/renderer/assets/logos/logoWithLabelBlue.svg
Labels: documentation, enhancement

#94 Fix/double reports
  package.json
  src/renderer/components/ConfigurationTable/ConfigurationTable.tsx
  src/renderer/components/FileCheckDropzone/FileCheckDropzone.tsx
  src/renderer/components/FileUploadStages/PickConfiguration/Stage2.tsx
  src/renderer/components/FileUploadStages/PickFiles/Stage1.tsx
  src/renderer/components/LastConfigurations/LastConfigurations.tsx
  src/renderer/components/LastPeriodicalChecks/LastPeriodicalChecks.tsx
  src/renderer/components/LastReports/LastReports.tsx
  src/renderer/reducers/ConfigurationReducer.ts
  src/renderer/reducers/ReportsReducer.ts
  src/renderer/theme/Default.tsx
Labels: bug, code, frontend

#95 report details chart fixed
  src/renderer/components/FileUploadStages/ProcessFiles/Stage3.tsx
  src/renderer/components/LastReports/LastReports.tsx
  src/renderer/components/ReportDetails/ReportDetails.tsx
  src/renderer/components/ReportsTable/ReportsTable.tsx
Labels: bug, code, frontend

#103 back => go
  src/renderer/components/ReportDetails/ReportDetails.tsx
  src/renderer/screens/ReportDetails/ReportDetails.tsx
  src/renderer/screens/Reports/Reports.tsx
  src/renderer/theme/Table.tsx
Labels: bug, code, frontend

#104 Feature/clean packagejson
  mocks/fileMock.js
  mocks/styleMock.js
  package.json
  src/main/main.ts
  src/renderer/actions/ReportActions.ts
  src/renderer/app.tsx
  src/renderer/components/FileCheckDropzone/FileCheckDropzone.tsx
  src/renderer/components/FileUploadStages/PickFiles/Stage1.tsx
  src/renderer/components/FileUploadStages/ProcessFiles/Stage3.tsx
  src/renderer/components/LastConfigurations/LastConfigurations.tsx
  src/renderer/components/LastPeriodicalChecks/LastPeriodicalChecks.tsx
  src/renderer/components/LastReports/LastReports.tsx
  src/renderer/components/ReportsTable/ReportsTable.tsx
  src/renderer/reducers/ConfigurationReducer.ts
  src/renderer/reducers/FileCheckReducer.ts
  src/renderer/reducers/ReportsReducer.ts
  src/renderer/screens/Dashboard/Dashboard.tsx
  src/renderer/screens/FileChecks/FileChecks.tsx
  src/renderer/screens/Reports/Reports.tsx
  test/components/Counter.spec.tsx
  test/components/__snapshots__/Counter.spec.tsx.snap
  test/e2e/example.spec.ts
  webpack-config/webpack.base.config.js
Labels: code, enhancement, frontend

#105 router problem fixed
  src/renderer/actions/ReportActions.ts
  src/renderer/components/ConfigurationTable/ConfigurationTable.tsx
  src/renderer/components/FileUploadStages/ProcessFiles/Stage3.tsx
  src/renderer/components/LastReports/LastReports.tsx
  src/renderer/components/ReportsTable/ReportsTable.tsx
  src/renderer/reducers/ReportsReducer.ts
  src/renderer/screens/Application.tsx
  src/renderer/screens/ReportDetails/ReportDetails.tsx
  src/renderer/screens/Reports/Reports.tsx
Labels: bug, code, frontend

#106 Fix/white screen
  webpack-config/webpack.base.config.js
Labels: bug, frontend

#113 Fix/duplicate files
  src/renderer/components/FileUploadStages/PickFiles/Stage1.tsx
  src/renderer/screens/About/About.tsx
Labels: bug, code, frontend

#115 Fix/mac os
  build/icon.ico
  build/icon.png
  build/logo.png
  src/renderer/reducers/ConfigurationReducer.ts
  src/renderer/reducers/ReportsReducer.ts
Labels: bug, code, frontend

#116 configuration name length => min: 1 & max: 20
  src/renderer/components/CreateConfigStages/NameSetter/NameSetter.tsx
  src/renderer/screens/ReportDetails/ReportDetails.tsx
Labels: bug, code, frontend

#108 Style/fixes
  src/renderer/assets/icons/icons8-add-file-500.svg
  src/renderer/components/Buttons/MainButton/MainButton.tsx
  src/renderer/components/Buttons/TextButton/TextButton.tsx
  src/renderer/components/CreateConfigStages/AddPolicy/AddPolicy.tsx
  src/renderer/components/CreateConfigStages/NameSetter/NameSetter.tsx
  src/renderer/components/CreateConfigStages/PolicyChecker/PolicyChecker.tsx
  src/renderer/components/CreateConfigStages/Report/Report.tsx
  src/renderer/components/CreateConfigStages/StandardPick/StandardPick.tsx
  src/renderer/components/CreateConfigStages/Summary/Summary.tsx
  src/renderer/components/FileUploadStages/PickConfiguration/Stage2.tsx
  src/renderer/components/FileUploadStages/PickFiles/Stage1.tsx
  src/renderer/components/FileUploadStages/ProcessFiles/Stage3.tsx
  src/renderer/components/ReportDetails/ReportDetails.tsx
  src/renderer/components/ReportsTable/ReportsTable.tsx
  src/renderer/screens/Configuration/Configuration.tsx
  src/renderer/screens/FileChecks/FileChecks.tsx
Labels: frontend

#119 Fix styling issues
  src/renderer/components/ReportDetails/ReportDetails.tsx
  src/renderer/screens/ReportDetails/ReportDetails.tsx
Labels: bug, code, frontend

#121 css fixes
  src/renderer/components/FileUploadStages/ProcessFiles/Stage3.tsx
  src/renderer/components/LastConfigurations/LastConfigurations.tsx
  src/renderer/components/LastReports/LastReports.tsx
  src/renderer/styles/app.css
  src/renderer/theme/Main.tsx
  src/renderer/theme/Table.tsx
Labels: bug, code, frontend

#122 Update README.md
  README.md
Labels: documentation

#123 Develop to master feature
  package.json
  src/renderer/components/ReportDetails/ReportDetails.tsx
  src/renderer/screens/ReportDetails/ReportDetails.tsx
  test/e2e/example.spec.ts
Labels: code, frontend

#125 Remove unused folder
  test/e2e/example.spec.ts
Labels: bug
